name: check for upstream updates

on:
  schedule:
  - cron: "20 4 * * *"

jobs:
  check_updates:
    strategy:
      fail-fast: false
      matrix:
        ebuild:
        - sys-apps/qcontrol
        - sys-firmware/panfrost-firmware
        include:
        - ebuild: sys-apps/qcontrol
          feed: https://www.hellion.org.uk/qcontrol/releases/index.atom
        - ebuild: sys-firmware/panfrost-firmware
          feed: https://gitlab.com/rk3588_linux/linux/libmali.atom
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.5.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: ${{ matrix.feed }}
        labels: ${{ matrix.ebuild }}
