name: check for upstream updates

on:
  schedule:
    - cron: "20 4 * * *"

permissions: {}

jobs:
  check_updates:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    strategy:
      fail-fast: false
      matrix:
        ebuild:
          - media-sound/navidrome
          - sys-apps/qcontrol
          - sys-firmware/panfrost-firmware
        include:
          - ebuild: media-sound/navidrome
            feed: https://github.com/navidrome/navidrome/releases.atom
          - ebuild: sys-apps/qcontrol
            feed: https://www.hellion.org.uk/qcontrol/releases/index.atom
          - ebuild: sys-firmware/panfrost-firmware
            feed: https://gitlab.com/rk3588_linux/linux/libmali.atom

    steps:
      - uses: git-for-windows/rss-to-issues@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feed: ${{ matrix.feed }}
          labels: ${{ matrix.ebuild }}
